### ISSUE TITLE
Remove code block splitting

### ISSUE THREAD

**Issue by mxstbr** [SamyPesse/draft-js-code#21]
`draft-js-code` strength is handling what happens inside a code block. I think the module should focus more on that strength.

There's a lot of other modules (like the markdown or WYSIWYG plugins) that add the UX for getting into and out of code blocks. `draft-js-code` is awesome alongside those modules. At the moment it's in a weird spot where it doesn't help users get into code blocks but it helps them split and exit code blocks, which doesn't make much sense to me.

Rather than try to be a full-on solution for everything code, **I want `draft-js-code` to be the go-to module for everything that happens inside of a code block.**

In the next major version upgrade (1.0) I want to remove the code block splitting functionality. It's only like 4 lines of code, so the "depreciation notice" would be a note in the changelog to add those 4 lines of code to your own app manually.

If nobody objects to this plan I'll go ahead and make it happen, and then focus on inside-code-block improvements like #12 and #7!

**Comment by williamboman** [comment]
I'm 👍 on this. I currently override the return handler to avoid this from happening.

**Comment by mxstbr** [comment]
Going to give it a couple of days, then cut a major if nobody's objected until then. :blush:

**Comment by mxstbr** [comment]
It's been a month and nobody's objected, so I'm going to ship this change!

**Comment by mxstbr** [comment]
Done in #23, going to release as `v1.0` soon!

**Comment by mxstbr** [comment]
Released as `v0.3.0` instead! (since that's a major version pre-1.0 anyway)
