### ISSUE TITLE
Documentation: readme

### ISSUE THREAD

**Issue by heretoinfinity** [SamyPesse/draft-js-code#25]
Please clarify what e is in the lines of code below in the readme.md under the 'Usage' section. 

```
if (!CodeUtils.hasSelectionInBlock(editorState)) return Draft.getDefaultKeyBinding(e);
```
```
    return command || Draft.getDefaultKeyBinding(e);
```
The code as is generates this error:

![image](https://user-images.githubusercontent.com/23157966/31157320-07d6ed92-a888-11e7-8f00-a97b29db487b.png)

**Comment by mxstbr** [comment]
That's my bad, it should be `Draft.getDefaultKeyBinding(evt)`! PR welcome.

**Comment by heretoinfinity** [comment]
Pull request submitted

**Comment by mxstbr** [comment]
Awesome, merged! Thank you @heretoinfinity!
